[[redirects]]
  from = "/*"
  to = "https://openzeppelin.com"
  status = 301

[[redirects]]
  from = "/about"
  to = "https://openzeppelin.com/about"
  status = 301

[[redirects]]
  from = "/jobs/*"
  to = "https://openzeppelin.com/jobs/:splat"
  status = 301

[[redirects]]
  from = "/security-audits"
  to = "https://openzeppelin.com/security-audits"
  status = 301
